export file_name='model01ampl.dat'
export name='saida01.txt'
ampl PCH.run
export file_name='model02ampl.dat'
export name='saida02.txt'
ampl PCH.run
export file_name='model03ampl.dat'
export name='saida03.txt'
ampl PCH.run
export file_name='model04ampl.dat'
export name='saida04.txt'
ampl PCH.run
export file_name='model05ampl.dat'
export name='saida05.txt'
ampl PCH.run
export file_name='model06ampl.dat'
export name='saida06.txt'
ampl PCH.run
export file_name='model07ampl.dat'
export name='saida07.txt'
ampl PCH.run
export file_name='model08ampl.dat'
export name='saida08.txt'
ampl PCH.run
export file_name='model09ampl.dat'
export name='saida09.txt'
ampl PCH.run
export file_name='model10ampl.dat'
export name='saida10.txt'
ampl PCH.run
export file_name='model11ampl.dat'
export name='saida11.txt'
ampl PCH.run
export file_name='model12ampl.dat'
export name='saida12.txt'
ampl PCH.run
export file_name='model13ampl.dat'
export name='saida13.txt'
ampl PCH.run
export file_name='model14ampl.dat'
export name='saida14.txt'
ampl PCH.run
export file_name='model15ampl.dat'
export name='saida15.txt'
ampl PCH.run
export file_name='model16ampl.dat'
export name='saida16.txt'
ampl PCH.run
export file_name='model17ampl.dat'
export name='saida17.txt'
ampl PCH.run
export file_name='model18ampl.dat'
export name='saida18.txt'
ampl PCH.run
export file_name='model19ampl.dat'
export name='saida19.txt'
ampl PCH.run
export file_name='model20ampl.dat'
export name='saida20.txt'
ampl PCH.run
export file_name='model21ampl.dat'
export name='saida21.txt'
ampl PCH.run
export file_name='model22ampl.dat'
export name='saida22.txt'
ampl PCH.run
export file_name='model23ampl.dat'
export name='saida23.txt'
ampl PCH.run
export file_name='model24ampl.dat'
export name='saida24.txt'
ampl PCH.run
export file_name='model25ampl.dat'
export name='saida25.txt'
ampl PCH.run
export file_name='model26ampl.dat'
export name='saida26.txt'
ampl PCH.run
export file_name='model27ampl.dat'
export name='saida27.txt'
ampl PCH.run
